apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-home
  template:
    metadata:
      labels:
        app: nginx-home
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-mobile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-mobile
  template:
    metadata:
      labels:
        app: httpd-mobile
    spec:
      containers:
      - name: httpd
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat-laptop
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: tomcat-laptop
  template: 
    metadata: 
      labels: 
        app: tomcat-laptop
    spec: 
      containers: 
      - name: tomcat
        image: tomcat:latest 
        ports: 
        - containerPort: 8080
