apiVersion: v1
kind: Service
metadata:
  name: my-svc-home
spec:
  selector:
    app: nginx-home
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-mobile
spec:
  selector:
    app: httpd-mobile
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: my-svc-laptop
spec: 
  selector: 
    app: tomcat-laptop
  ports: 
  - port: 8080
    targetPort: 8080

