apiVersion: v1
kind: Service
metadata: 
  name: my-svc
  labels: 
    app: myapp
    env: devops
spec: 
  type: NodePort
  selector: 
    app: myapp
  ports: 
    - name: myport
      protocol: TCP
      port: 80
      targetPort: 80
