apiVersion: v1
kind: Service
metadata:
  name: studentapp
spec:
  type: NodePort
  selector:
    app: studentapp
  ports:
  - port: {{ .Values.studentapp.port }}
    targetPort: {{ .Values.studentapp.port }}

