apiVersion: v1
kind: Service
metadata: 
  name: apache-service
  labels: 
    app: apache
    env: devops
  namespace: apache
spec: 
  type: ClusterIP
  selector: 
    app: apache
  ports: 
    - name: myapacheport
      protocol: TCP
      port: 80
      targetPort: 80
