apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cbz-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: cbz.com
    http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-svc-home
            port:
              number: 80
      - path: /mobile(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-svc-mobile
            port:
              number: 80

