apiVersion: v1
kind: Service
metadata: 
  name: student-service
  labels: 
    app: student
    env: devops
  namespace: student
spec: 
  type: NodePort
  selector: 
    app: student
  ports: 
    - name: student-port
      protocol: TCP
      port: 8080
      targetPort: 8080
